name: Run Build Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/build-tests.yml@dev
    with:
      pre_install_pip: "git+https://github.com/OpenVoiceOS/ovos-plugin-manager@dev"
      install_extras: "test"
      test_path: "test/"
    secrets: inherit
