name: Coverage Report
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    with:
      pre_install_pip: "git+https://github.com/OpenVoiceOS/ovos-plugin-manager@dev"
      test_extras: "test"
      test_path: "test/"
    secrets: inherit
